name: Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install Haxelib Dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib install flixel --quiet
          haxelib install flixel-addons --quiet
          haxelib install flixel-tools --quiet
          haxelib install hxcpp --quiet

      - name: Setup Lime
        run: |
          haxelib run lime setup
          haxelib run lime setup android

      - name: Build Android
        run: |
          haxelib run lime build android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Prototype (Android)
          path: export/release/android/bin/app/build/outputs/apk/debug/*.apk
