name: Android Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Cache Haxelib
        uses: actions/cache@v4
        with:
          path: ~/haxelib
          key: haxelib-${{ hashFiles('**/Project.xml') }}
          restore-keys: haxelib-

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib

          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git
          
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install tjson
          haxelib install actuate

      - name: Setup Android SDK
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2" \
          "ndk;25.2.9519653"

      - name: Configure Lime
        run: |
          haxelib run lime setup android -accept

          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_HOME/ndk/25.2.9519653
          haxelib run lime config JAVA_HOME $JAVA_HOME

      - name: Gradle Memory Fix
  run: |
    mkdir -p ~/.gradle
    echo "org.gradle.jvmargs=-Xmx4096M" >> ~/.gradle/gradle.properties

      - name: Clean
        run: |
          rm -rf export
          rm -rf .gradle

      - name: Compile
        env:
          GRADLE_OPTS: -Xmx4g
        run: |
          haxelib run lime build android -debug

      - uses: actions/upload-artifact@v4
        with:
          name: Prototype-Android
          path: export/android/bin/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
